services:
    mongodb:
        container_name: 'gt-mongo'
        image: mongodb/mongodb-community-server:latest
        ports:
            - 27017:27017
        volumes:
            - gt-mongo-data:/data/db:rw
        command: mongod --replSet rs0 --bind_ip_all
        healthcheck:
            test: |
                echo "
                try {
                    rs.status().ok
                } catch (err) {
                    rs.initiate({
                        _id: 'rs0',
                        members: [{ _id: 0, host: 'localhost:27017' }]
                    }).ok
                }
                " | mongosh --quiet
            interval: 5s
            timeout: 30s
            start_period: 10s
            retries: 30

volumes:
  gt-mongo-data: 
    name: "GT_MongoDB_data"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIRECTORY}/mongodb