apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: docker-registry-pv-claim
    namespace: docker-registry
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi