replicaCount: 1
peristence:
    enabled: true
    size: 10Gi
    deleteEnabled: true
    storageClass: csi-cinder-classic
    existingClaim: docker-registry-pv-claim
secrets:
    htpasswd: terrybd:$2y$05$PXv51uhxgid8AvwQKf0ZNuKQmRhoowJ9V./q3k5lbxpJ2WR2jYrUO